### ISSUE TITLE
加入GTNL之后，NEI刷不出物品

### ISSUE THREAD

**Issue by AxuriB** [ABKQPO/GT-Not-Leisure#4]
<img width="1565" alt="4B8893C04F6FFA0E4D877EAB1C869021" src="https://github.com/user-attachments/assets/68799c3c-af5e-4b27-a605-c476ca072713" />
版本是270
其他私货mod有TST，123，可编程仓室，NH-Utilities，AE2things，万宁nh，万宁鸿蒙

**Comment by ABKQPO** [comment]
日志和版本号

**Comment by AxuriB** [comment]
[latest.log](https://github.com/user-attachments/files/18264869/latest.log)
GTNH版本是2.7.0，GTNL的版本是0.1.4

**Comment by ABKQPO** [comment]
你确定不是其他私货造成的问题吗

**Comment by AxuriB** [comment]
TST0.6.1装了就刷不出nei

**Comment by AxuriB** [comment]
大佬能救救孩子吗

**Comment by ABKQPO** [comment]
我这边加了tst0.6.1没问题

**Comment by AxuriB** [comment]
我重装了一遍，只装GTNL和TST都刷不出NEI

**Comment by AxuriB** [comment]
需要我提供什么日志吗？还是说要更新什么mod？

**Comment by ABKQPO** [comment]
只加tst或nl能出来吗

**Comment by AxuriB** [comment]
可以的，我试过我全部私货都加上，然后单独只加TST或者GTNL都能正常出NEI，但是其他的全部删掉，只装TST和GTNL都刷不出NEI，重新安装也尝试过

**Comment by ABKQPO** [comment]
你用的jdk17还是java8

**Comment by AxuriB** [comment]
java8

**Comment by ABKQPO** [comment]
试试这个
https://down.wss.zone/295xbl0/f/x9/fx9p295xbl0?cdn_sign=1735452010-97-0-a7cb4bcaea1b30dc4f12762fbb12c61f&exp=1200&response-content-disposition=attachment%3B%20filename%3D%22ScienceNotLeisure-v0.1.4-master.1%2B441890ce42-dirty.jar%22%3B%20filename%2A%3Dutf-8%27%27ScienceNotLeisure-v0.1.4-master.1%252B441890ce42-dirty.jar

**Comment by AxuriB** [comment]
网站进不去

**Comment by ABKQPO** [comment]
https://github.com/ABKQPO/GT-Not-Leisure/releases/download/v0.1.4-fix/ScienceNotLeisure-v0.1.4-master.1+441890ce42-dirty.jar

**Comment by AxuriB** [comment]
尝试了，一样的，刷不出NEI

**Comment by ABKQPO** [comment]
按下o看看

**Comment by AxuriB** [comment]
按O键之后nei隐藏了，然后再按下就显示了，也还是一样的刷不出nei

**Comment by AxuriB** [comment]
271版本是可以刷出nei的

**Comment by ABKQPO** [comment]
更新tst，目前无法复现这个问题

**Comment by AxuriB** [comment]
tst最新版是0.6.2，我已经更新了，在270版本也依然是不出nei，我再重装一下，单独装GTNL和TST试试

**Comment by AxuriB** [comment]
佬哥，我在尝试了很多遍之后，我发现这个好像跟lang有关系，我271直接把所有私货mod都丢进去然后其他的不动直接启动，进游戏就能刷出NEI，但是除了一些基础的是中文，像铜杆，铜齿轮和机器名字都是英文。然后我同样的基础上，再去下了最新的汉化包丢进去，再进游戏就刷不出NEI，我不太懂什么原理，佬哥有什么头绪吗

**Comment by AxuriB** [comment]
佬哥，271能刷出nei是这样才能出来，就是mod全部装进去，然后直接进去不行，我更新了安洁莉卡，所以第一次进的时候报了个mod重复，然后再去弄下再进，进游戏就会出现我之前说的那种，刷出nei但是都是英文，这跟java版本有关系吗？我再去试试java21看看

**Comment by AxuriB** [comment]
不折腾了，单独只上GTNL和TST，不管是270还是271，java哪个版本都刷不出nei，就我说的那种情况能刷出来一次，佬哥能找到原因就修吧，折腾两天了

**Comment by AxuriB** [comment]
TST不能有中文名字，有就会导致NEI出不来，已经解决了
